Fixed unexpected behaviour of returning an index less than the length…
k42-software/go-altcha pull request #3
Opened 2024-05-16 16:56 UTC by mklnz

Due to slice ordering, when using sort.SearchStrings the return result is based on the ordering of the existing list.
So the index returned could be less than len(list), depending on existing entries.

Replaced the check with a simple nested for loop to check for exact value instead of using sort.SearchStrings

2024-05-24 15:34 UTC, astrolox commented
@mklnz please remove the change the module name and I'll merge the PR

2024-05-24 15:35 UTC, astrolox requested changes

2024-05-24 15:35 UTC, astrolox commented on go.mod
> -module github.com/k42-software/go-altcha
I am unable to accept this change

2024-05-24 15:35 UTC, astrolox commented on replay.go
> +			}
LGTM

2024-05-28 18:23 UTC, mklnz commented
Fixed sorry

2024-05-28 19:16 UTC, astrolox approved these changes

2024-05-28 19:16 UTC, merged

2024-05-28 19:17 UTC, astrolox commented
@mklnz Thanks for the bug fix :grin: